app:
  version: ^project.version^
  name: ^project.name^

spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    url: ${URL_DATA:jdbc:postgresql://localhost:5432/SEMIP}
    username: ${USER_DATA:postgres}
    password: ${PW_DATA:123}
    driverClassName: org.postgresql.Driver
  data:
    mongodb:
      host: ${URL_DOCUMENT:127.0.0.1}
      port: 27017
      database: ${DB_DOCUMENT:repo_receta}

eureka:
  instance:
    metadata-map:
      management:
        port: 9090

ms-rioblanco.url: http://200.42.173.148:8080/rioblanco/v1/
ms-foleador.url: ${MS_FOLEADOR:http://localhost:8087/semipFoleador/v1/}

security:
  sessions: stateless
  basic:
    enabled: false
  user:
    password: none    
  oauth2:
    resource:
      jwt:
        keyValue: |
            -----BEGIN PUBLIC KEY-----
            MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo1jWPfjvJxaXCHzvClU7
            uJg+6AlZ8ht1Rbr+7Wo5o+YBWgCc6lZmSv/mwxvfL/wqagQ/W756a8vUJ7qFz/k9
            eBSJQSRuzJ6pT4OMMR9gbmYroh3RM/Xd5RelJgT3+OrvjAZr1pFYdAwp0q1T9XPa
            6PnCXq8KhIqNPxMjcaBrOycWEgWE4g4VnnrKDLtMmEZZIc0EMv8j7womsyNkbTyl
            nPsbFttNwtFoTVJeqvD01Fd6ISaoOVQAUfAcxvp77B/A1g0No3GHBupEtW3Hgp2/
            80Zl0+Gwjl6Wag5Mu9H7MIUPo+4xFGAJ0uwseHiErZqdWlHIo179IacB87+9Vt0g
            pwIDAQAB
            -----END PUBLIC KEY-----

